feat: migrate switch button to new colors
scaleway/scaleway-ui pull request #1038
Opened 2021-12-21 14:12 UTC by DorianMaliszewski

## Summary

## Type

- Enhancement

### Summarise concisely:

#### What is expected?

Use new colors in switch button

## Relevant logs and/or screenshots

| Page |   Before   |      After |
| :--- | :--------: | ---------: |
| url  | screenshot | screenshot |
| url  | screenshot | screenshot |

2021-12-21 15:19 UTC, QuiiBz approved these changes

2021-12-21 15:19 UTC, QuiiBz commented on src/components/SwitchButton/index.tsx
> +      &:not([aria-checked='true']):not([aria-disabled='true']) {
Can't we do this? It's only not supported in IE https://developer.mozilla.org/fr/docs/Web/CSS/:not#compatibilit%C3%A9_des_navigateurs

```suggestion
      &:not([aria-checked='true'], [aria-disabled='true']) {
```

2021-12-22 09:53 UTC, matthprost requested changes

2021-12-22 09:53 UTC, matthprost commented on src/components/SwitchButton/index.tsx
> +      background-color: ${theme.colors.neutral.backgroundWeak};
Why adding background while it wasn't there before ?

2021-12-28 13:46 UTC, vincentaudebert approved these changes

2021-12-31 14:50 UTC, merged