ci: init visual testing with loki
scaleway/scaleway-ui pull request #1162
Opened 2022-02-07 16:12 UTC by vincentaudebert

## Summary

## Type

- Feature

### Summarise concisely:

#### What is expected?

Visual testing in pipeline

#### The following changes where made:

(Describe what you did)

1. Adds loki to visual test components based on storybook stories

2022-02-07 17:11 UTC, vincentaudebert commented
Note to myself: reset matrix on test + build ---- node: ["14", "16", "17"]

2022-02-09 15:40 UTC, vincentaudebert commented on src/components/Placeholder/__stories__/index.stories.tsx
> +console.log(Math.random(), Math.random(), Math.random())
Indeed 😅 fixed

2022-02-09 15:50 UTC, adriengibrat approved these changes

2022-02-10 10:52 UTC, chambo-e requested changes

2022-02-10 12:58 UTC, vincentaudebert commented on .github/workflows/ci.yml
> +      - uses: actions/cache@v2
@chambo-e No this is caching the build to be used later on in the "visual" job

Artefacts are stored there

2022-02-10 13:00 UTC, vincentaudebert commented on .github/workflows/ci.yml
> +  build-storybook-visual:
Not sure I get it? This is the first step for visual testing CI. (if you check loki, they do build storybook then they run the visual testing. We need to build first to target local build with loki

2022-02-10 15:20 UTC, chambo-e commented on .github/workflows/ci.yml
> +  build-storybook-visual:
This workflow is performed onto every pull requests and every push on main

As we only want this on pull requests we could have a dedicated Visual Testing pipeline subscribed only to PR events :)

2022-02-10 15:20 UTC, chambo-e commented on .github/workflows/ci.yml
> +      - uses: actions/cache@v2
The build is an artefact no ?

2022-02-11 10:09 UTC, matthprost requested changes
Isn't github repo gonna be super heavy to clone with all those pictures ? Is this the only way to keep them locally ? Cc @chambo-e

2022-02-14 09:52 UTC, chambo-e commented
> Isn't github repo gonna be super heavy to clone with all those pictures ? Is this the only way to keep them locally ? Cc @chambo-e

@matthprost there is only 3~Mb of png, I think we can handle it for now :)

2022-02-16 09:20 UTC, vincentaudebert commented on .github/workflows/ci.yml
> +      - uses: actions/cache@v2
@chambo-e i used this to decide, i think it's pretty complete

https://levelup.gitconnected.com/github-actions-how-to-share-data-between-jobs-fc1547defc3e

2022-02-16 09:23 UTC, vincentaudebert commented on .github/workflows/ci.yml
> +  build-storybook-visual:
@chambo-e good point. I'm on it

2022-02-16 15:43 UTC, chambo-e requested changes

2022-02-16 15:43 UTC, chambo-e commented on package.json
> +    "visual:test": "yarn loki test"
```suggestion
    "test:visual:update": "yarn run build:storybook-visual && yarn loki update",
    "test:visual": "yarn loki test"
```

To stay consistent with other test commands

2022-02-16 15:43 UTC, chambo-e commented on package.json
> +    "jest-mock-random": "^1.1.1",
```suggestion
    "jest-mock-random": "1.1.1",
```

2022-02-16 15:43 UTC, chambo-e commented on package.json
> +    "loki": "^0.28.1",
```suggestion
    "loki": "0.28.1",
```

2022-02-17 15:18 UTC, merged