feat: text component
scaleway/scaleway-ui pull request #1541
Opened 2022-06-02 14:54 UTC by vincentaudebert

## Summary

## Type

- Feature

### Summarise concisely:

#### What is expected?

New Text component

#### The following changes where made:

(Describe what you did)

1. Adds Text component to SWUI

## Relevant logs and/or screenshots

<img width="1039" alt="Screenshot 2022-06-06 at 12 31 41" src="https://user-images.githubusercontent.com/3360430/172144478-fa1d52cd-ee5e-4646-b730-0c0a23777a98.png">

2022-06-02 15:54 UTC, vincentaudebert commented
Known issue: tooltip doesn't trigger on first hover

Test coverage to improve + visual testing

2022-06-07 08:42 UTC, matthprost requested changes
Typography should be marked as deprecated with a description into storybook and should have `@deprecated` comment to mark it in JS/TS too

2022-06-07 08:48 UTC, matthprost requested changes

2022-06-07 08:48 UTC, matthprost commented on src/components/Text/index.tsx
> +}
There is also stronger as prominence but only for neutral variant

2022-06-07 15:37 UTC, matthprost requested changes

2022-06-08 11:14 UTC, matthprost approved these changes

2022-06-08 11:14 UTC, matthprost commented on src/components/Typography/index.tsx
> + * @deprecated Has been replaced by component Text, please this one instead.
```suggestion
 * @deprecated Has been replaced by component Text, please use this one instead.
```

2022-06-08 12:29 UTC, DorianMaliszewski approved these changes

2022-06-08 13:34 UTC, merged