Refactor/popper component
scaleway/scaleway-ui pull request #1564
Opened 2022-06-09 08:00 UTC by vincentaudebert

## Summary

## Type

- Refactor

### Summarise concisely:

#### What is expected?

Popper component is gone and moved into Menu (only place where it's used) in a simplified version.

#### The following changes where made:

(Describe what you did)

1. Move Popper directly into Menu

2. Nuke variants and useless things, clean code a bit

3.

## Relevant logs and/or screenshots

| Page |   Before   |      After |
| :--- | :--------: | ---------: |
| url  | 
<img width="216" alt="Screenshot 2022-06-09 at 09 59 32" src="https://user-images.githubusercontent.com/3360430/172796042-e3899916-9b54-486b-9748-9b2c6b10e15e.png">  | 
<img width="173" alt="Screenshot 2022-06-09 at 09 59 36" src="https://user-images.githubusercontent.com/3360430/172796069-2c062168-5bea-4140-8d2a-d2c19a06e988.png"> |

2022-06-09 08:12 UTC, chambo-e commented on src/components/Menu/index.tsx
> +  /* fill: ${({ theme }) => theme.colors.neutral.text}; */
Needs to be removed ?

2022-06-09 08:12 UTC, chambo-e commented on src/components/Menu/index.tsx
> +const Popper = ({
Instead of having a customisable Popper could we inline reakit popper in the Menu ?

2022-06-10 08:05 UTC, QuiiBz commented on src/components/Menu/index.tsx
> +  border-radius: 4px;
Can we use `theme.radii?`

2022-06-13 10:25 UTC, QuiiBz approved these changes

2022-06-13 15:02 UTC, matthprost requested changes
![Screenshot 2022-06-13 at 17 02 21](https://user-images.githubusercontent.com/15812968/173383970-5c786e5f-4696-47f7-af18-d7d988650a16.png)

@vincentaudebert I cannot build and so cannot test

2022-06-15 11:42 UTC, matthprost approved these changes

2022-06-15 11:46 UTC, merged