perf: reduce bundle size
scaleway/scaleway-ui pull request #1570
Opened 2022-06-09 12:45 UTC by matthprost

## Summary

## Type

- Optimisation

### Summarise concisely:

#### The following changes where made:

1. Removed 2 `.png` we have in phone number input to keep the best quality one. I also converted it into `.webp` which reduced size even more.

2. Removed `avatar.svg` in `Avatar` component, the image should be imported into the component and not be present in this library. ⚠️ This is might be breaking change as there is no more image as default value

## Relevant logs and/or screenshots

| Page |   Before   |      After |
| :--- | :--------: | ---------: |
| size  | <img width="212" alt="Screenshot 2022-06-09 at 14 42 44" src="https://user-images.githubusercontent.com/15812968/172849889-94f8d52a-aeb6-4be7-a813-2670ea94342c.png"> | <img width="225" alt="Screenshot 2022-06-09 at 14 42 10" src="https://user-images.githubusercontent.com/15812968/172849911-8432e9db-5f5c-47cf-bf13-949c0a30d015.png"> |

2022-06-10 08:13 UTC, QuiiBz commented
Flags are a bit buggy:

<img width="599" alt="Screenshot 2022-06-10 at 10 13 16" src="https://user-images.githubusercontent.com/43268759/173021846-a4356637-e0d8-4318-a40f-490fd6d20f02.png">

2022-06-10 15:17 UTC, matthprost commented
> Flags are a bit buggy:
> 
> <img alt="Screenshot 2022-06-10 at 10 13 16" width="599" src="https://user-images.githubusercontent.com/43268759/173021846-a4356637-e0d8-4318-a40f-490fd6d20f02.png">

Can you tell me your web browser ? On chrome it works fine for me 
<img width="528" alt="Screenshot 2022-06-10 at 17 16 49" src="https://user-images.githubusercontent.com/15812968/173097163-949053e8-cb03-4f36-a2a4-18566153a96e.png">

2022-06-10 19:34 UTC, QuiiBz commented
> 
> Can you tell me your web browser ? On chrome it works fine for me <img alt="Screenshot 2022-06-10 at 17 16 49" width="528" src="https://user-images.githubusercontent.com/15812968/173097163-949053e8-cb03-4f36-a2a4-18566153a96e.png">

Using Brave, Chrome, Firefox, and Safari, they all have the issue 🤔

![Screenshot 2022-06-10 at 21 33 40](https://user-images.githubusercontent.com/43268759/173137380-9e59dba7-49f2-46d8-b45f-2afb91c554d6.png)

2022-06-13 09:41 UTC, chambo-e requested changes

2022-06-13 09:41 UTC, chambo-e commented on src/utils/xor.ts
> +type Without<T, U> = { [P in Exclude<keyof T, keyof U>]?: never }
into global.d.ts :)

2022-06-16 08:57 UTC, vincentaudebert approved these changes

2022-06-16 09:16 UTC, QuiiBz approved these changes

2022-06-16 10:00 UTC, merged