fix(tokens): use hover and disabled from figma
scaleway/scaleway-ui pull request #1587
Opened 2022-06-15 12:24 UTC by matthprost

## Summary

## Type

- Enhancement

### Summarise concisely:

#### What is expected?

To use hover and disabled from figma and not from local. The script of sync to figma tokens has been update and I removed local overloaded values.

2022-06-15 12:27 UTC, chambo-e requested changes

2022-06-15 12:27 UTC, chambo-e commented on src/theme/tokens/dark.ts
>      secondary: {
Intended to loose all secondary colours ?

2022-06-15 13:26 UTC, chambo-e commented on src/theme/tokens/dark.ts
>      secondary: {
Alright :)

2022-06-16 09:01 UTC, vincentaudebert commented
lint + tests broken

2022-06-16 09:07 UTC, QuiiBz commented
Typography colors are a lot softer, is that intentional?

<img width="1480" alt="Screenshot 2022-06-16 at 11 06 06" src="https://user-images.githubusercontent.com/43268759/174035278-b16286da-a274-444e-85d0-24b59a00a380.png">

2022-06-16 15:12 UTC, matthprost commented
> Typography colors are a lot softer, is that intentional?
> 
> <img alt="Screenshot 2022-06-16 at 11 06 06" width="1480" src="https://user-images.githubusercontent.com/43268759/174035278-b16286da-a274-444e-85d0-24b59a00a380.png">

It seems like

2022-06-16 15:28 UTC, QuiiBz approved these changes

2022-06-22 10:23 UTC, merged