Fix/remove dep colors separator
scaleway/scaleway-ui pull request #1649
Opened 2022-07-06 10:18 UTC by vincentaudebert

## Summary

## Type

- Refactor

### Summarise concisely:

#### What is expected?

No more deprecated colors nor Box into Separator

#### The following changes where made:

(Describe what you did)

1. Remove colors deprecated + Box

2. Migrate SWUI elements using Separator

2022-07-06 14:36 UTC, matthprost requested changes

2022-07-06 14:36 UTC, matthprost commented on src/components/DateInput/index.tsx
> +  margin-right: ${({ theme }) => theme.space['1']};
```suggestion
  margin: 0 ${({ theme }) => theme.space['1']};
```

2022-07-07 06:55 UTC, philibea approved these changes

2022-07-07 07:03 UTC, matthprost approved these changes

2022-07-07 07:58 UTC, merged