feat(Notice): migrate from Box to div
scaleway/scaleway-ui pull request #1753
Opened 2022-08-10 14:23 UTC by chambo-e

2022-08-10 14:27 UTC, matthprost requested changes
It will also mean a migration on projects using Notice :)

2022-08-10 14:27 UTC, matthprost commented on src/components/TextBox/index.tsx
> +        {notice && <StyledNotice>{notice}</StyledNotice>}
```suggestion
        {notice ? <StyledNotice>{notice}</StyledNotice> : null}
```

2022-08-11 08:12 UTC, matthprost approved these changes

2022-08-11 14:01 UTC, baptisteArno approved these changes

2022-08-11 17:16 UTC, merged