feat(icons): add reboot icon
scaleway/scaleway-ui pull request #1824
Opened 2022-08-30 14:28 UTC by baptisteArno

## Summary

Add reboot icon

## Type

- Enhancement

## Relevant logs and/or screenshots

| Page |   Before   |      After |
| :--- | :--------: | ---------: |
| -  | - | <img width="392" alt="CleanShot 2022-08-30 at 16 27 45@2x" src="https://user-images.githubusercontent.com/16015833/187463741-ea621782-345b-4f8c-a9cc-198eeea0d73e.png"> |

2022-08-30 15:02 UTC, matthprost requested changes

2022-08-30 15:02 UTC, matthprost commented on src/components/Icon/index.tsx
> +    viewBox: '0 0 14 16',
Do we need to add another type of viewBox ?

2022-08-30 15:03 UTC, QuiiBz approved these changes

2022-08-30 15:23 UTC, matthprost requested changes

2022-08-30 15:23 UTC, matthprost commented on src/components/Icon/index.tsx
> +  },
You can remove this snippet :)

2022-08-31 12:19 UTC, matthprost approved these changes

2022-08-31 14:23 UTC, merged