fix: use `useId` instead of `useUUID`
scaleway/scaleway-ui pull request #1826
Opened 2022-08-30 14:54 UTC by QuiiBz

## Summary

Closes #1790

## Type

- Refactor

### Summarise concisely:

#### What is expected?

Use React 18 `useId` hook instead of `useUUID`.
Remove the exports from index of `useUUID` and `getUUID`.
I could not delete `getUUID` because it's still used in places where we can't use `useId`

2022-08-30 15:12 UTC, matthprost requested changes

2022-08-30 15:12 UTC, matthprost commented on src/utils/ids.ts
>    `${prefix ? `${prefix}-` : ''}${uuid()}`
To remove ?

2022-08-30 15:12 UTC, matthprost commented on src/utils/ids.ts
>  const uuid = () => Array.from({ length: 8 }, chr4).join('')
Maybe all the file actually

2022-08-30 15:13 UTC, matthprost requested changes

2022-08-30 15:13 UTC, matthprost commented on src/components/SelectableCard/__tests__/__snapshots__/index.tsx.snap
> +    aria-describedby=":rl:"
is that the normal format of id ??

2022-08-31 09:11 UTC, QuiiBz commented on src/utils/ids.ts
>  const uuid = () => Array.from({ length: 8 }, chr4).join('')
From the PR description:

> I could not delete `getUUID` because it's still used in places where we can't use `useId`

2022-08-31 09:12 UTC, QuiiBz commented on src/components/SelectableCard/__tests__/__snapshots__/index.tsx.snap
> +    aria-describedby=":rl:"
Yes

2022-08-31 11:39 UTC, matthprost approved these changes

2022-08-31 12:02 UTC, merged