feat: change loader by placeholder in List
scaleway/scaleway-ui pull request #1828
Opened 2022-08-30 15:51 UTC by Lawndlwd

## Summary

## Type

- Feature

Replace classic loader with the list placeholder

2022-08-31 11:45 UTC, Lawndlwd commented
TODO: add default perPage

2022-09-01 08:59 UTC, matthprost commented on src/components/List/index.tsx
> +    perPage = 2,
Why?

2022-09-01 09:06 UTC, baptisteArno requested changes

2022-09-01 13:29 UTC, matthprost approved these changes

2022-09-01 13:36 UTC, baptisteArno commented
That still doesn't feel right IMO

<img width="1313" alt="CleanShot 2022-09-01 at 15 34 03@2x" src="https://user-images.githubusercontent.com/16015833/187927095-fb3b2da0-2d2c-4e52-b1ec-717744987508.png">

Here I would expect 3 lines per row (none for the checkbox column) and each line would have the width of the row

2022-09-01 14:17 UTC, Lawndlwd commented
> Here I would expect 3 lines per row (none for the checkbox column) and each line would have the width of the row

the 4th line not for the checkbox, it is for unlabelled col that contain action,
yeah, I tried to get style from the list it so complicated, i prefer to go with this for now @baptisteArno

2022-09-02 06:49 UTC, philibea approved these changes

2022-09-02 10:20 UTC, baptisteArno approved these changes

2022-09-02 10:21 UTC, merged