fix(richselect): multi value padding without top label
scaleway/scaleway-ui pull request #1837
Opened 2022-09-07 08:49 UTC by baptisteArno

## Summary

Fix top padding when rich select has multi values and `noTopLabel` enabeld

## Type

- Bug

## Relevant logs and/or screenshots

| Before | After |
| :-: | :-: |
|  <img width="375" alt="CleanShot 2022-09-07 at 10 41 37@2x" src="https://user-images.githubusercontent.com/16015833/188834187-c35e4feb-7025-47a4-bcb9-66626848df6e.png"> | <img width="347" alt="CleanShot 2022-09-07 at 10 41 02@2x" src="https://user-images.githubusercontent.com/16015833/188834393-c4609dbc-3724-4c9a-9f89-a95d884b64e1.png"> |

2022-09-07 09:59 UTC, matthprost requested changes

2022-09-07 09:59 UTC, matthprost commented on src/components/RichSelect/index.tsx
> +    marginTop: noTopLabel ? '4px' : '11px',
Could we use `theme.space['0.5']` ?

2022-09-08 08:07 UTC, baptisteArno commented
Also improved spacing when top label is present IMO:

| Before | After |
| :-: | :-: |
| <img width="734" alt="CleanShot 2022-09-08 at 10 06 15@2x" src="https://user-images.githubusercontent.com/16015833/189069644-86f52862-f09f-4e4f-a482-8ab1c365bb2a.png"> | <img width="677" alt="CleanShot 2022-09-08 at 10 06 27@2x" src="https://user-images.githubusercontent.com/16015833/189069676-d757a0bb-9405-43cc-aab4-63535ac4664d.png"> |

2022-09-08 08:15 UTC, QuiiBz commented on src/components/RichSelect/index.tsx
> +    marginTop: noTopLabel ? theme.space['0.5'] : '16px',
We can use `theme.space['2']` instead of hardcoding `16px`

2022-09-08 09:17 UTC, QuiiBz approved these changes

2022-09-09 14:25 UTC, philibea approved these changes

2022-09-09 14:29 UTC, matthprost approved these changes

2022-09-09 14:29 UTC, merged