feat: make pagination easy to use
scaleway/scaleway-ui pull request #1894
Opened 2022-09-22 14:54 UTC by DorianMaliszewski

## Summary

## Type

- Feature

### Summarise concisely:

#### What is expected?

New pagination component. Need to refactor List to drop the old Pagination component

#### The following changes where made:

1. Simplify Pagination component

## Relevant logs and/or screenshots

<img width="1149" alt="Capture d’écran 2022-09-22 à 16 53 54" src="https://user-images.githubusercontent.com/24531136/191780713-4b60895b-6e56-4a44-aeed-522d8ba4704a.png">

2022-09-22 16:32 UTC, matthprost requested changes

2022-09-22 16:32 UTC, matthprost commented on src/components/PaginationV2/index.tsx
> +  height: ${({ theme }) => theme.space['6']};
please do not use space for sizing, it is reserved for spacing (padding, margin, etc)

2022-09-22 16:32 UTC, matthprost commented on src/components/PaginationV2/index.tsx
> +  height: ${({ theme }) => theme.space['6']};
same here ?

2022-09-22 16:32 UTC, matthprost commented on src/components/PaginationV2/index.tsx
> +  line-height: ${({ theme }) => theme.space['3']};
maybe you can use `theme.typography.body.lineHeight` instead

2022-09-22 16:32 UTC, matthprost commented on src/components/PaginationV2/index.tsx
> +  font-weight: 500;
Same here can we use it from theme or use `Text` component ?

2022-09-22 16:32 UTC, matthprost commented on src/components/PaginationV2/index.tsx
> +  }
All of those functions call be `useCallBack` no ?

2022-09-22 16:32 UTC, matthprost commented on src/components/PaginationV2/index.tsx
> +  }
this one too

2022-09-22 16:32 UTC, matthprost commented on src/components/PaginationV2/index.tsx
> +}
can be removed we don't specify proptypes ad it is typescript

2022-09-23 14:05 UTC, QuiiBz commented on src/components/PaginationV2/getPageNumbers.ts
> +    end = end + remaining > pageCount ? pageCount : end + remaining
```suggestion
    end = Math.min(end + remaining, pageCount)
```

2022-09-23 14:05 UTC, QuiiBz commented on src/components/PaginationV2/index.tsx
> +    <div style={{ display: 'flex' }}>
Maybe better to use `styled` instead?

2022-09-26 14:21 UTC, baptisteArno approved these changes
lgtm

2022-09-26 14:36 UTC, merged