fix(pagination): don't update page count when list is loading
scaleway/scaleway-ui pull request #1902
Opened 2022-09-26 13:54 UTC by baptisteArno

## Summary

Make sure that pagination isn't updated while the parent list is loading.

## Type

- Enhancement

2022-09-26 14:12 UTC, matthprost requested changes

2022-09-26 14:12 UTC, matthprost commented on src/components/List/index.tsx
> +    isListLoading: isLoading,
use `isLoading` would be a better fit no?

2022-09-26 14:18 UTC, DorianMaliszewski approved these changes
LGTM after @matthprost feedback

2022-09-27 08:02 UTC, matthprost approved these changes

2022-09-27 08:03 UTC, merged