fix(PieChart): allow scroll overflow on Legend
scaleway/scaleway-ui pull request #1906
Opened 2022-09-27 15:45 UTC by chambo-e

## Summary

## Type

- Enhancement

### Summarise concisely:

#### What is expected?

https://user-images.githubusercontent.com/2802867/192573190-f26725e9-90ae-4603-94a2-37cf69afb501.mov

2022-09-27 15:57 UTC, matthprost requested changes

2022-09-27 15:57 UTC, matthprost commented on src/components/PieChart/Legends.tsx
> +  overflow: scroll;
```suggestion
  overflow-y: scroll;
```

maybe to avoid unwanted scrolls

2022-09-28 08:58 UTC, matthprost approved these changes

2022-09-28 16:54 UTC, baptisteArno approved these changes

2022-09-28 17:22 UTC, merged