refactor: update storybook action bar / alert / avatar
scaleway/scaleway-ui pull request #1966
Opened 2022-10-19 09:18 UTC by baptisteArno

## Summary

Rewrite stories of `ActionBar`, `Alert` and `Avatar`

## Type

- Refactor

2022-10-19 14:00 UTC, matthprost requested changes

2022-10-20 08:10 UTC, QuiiBz commented
Can we have the radio selected by default with `standard` for `variant` and `warning` for `type`?

![image](https://user-images.githubusercontent.com/43268759/196893034-134cba31-540e-41e4-bf0f-bc83ed311262.png)

2022-10-20 11:36 UTC, QuiiBz approved these changes

2022-10-20 11:38 UTC, matthprost approved these changes

2022-10-20 11:38 UTC, merged