refactor(markdown): remove box from MarkDown
scaleway/scaleway-ui pull request #1975
Opened 2022-10-21 15:15 UTC by baptisteArno

## Summary

Remove Box from `MarkDown`

2022-10-23 13:23 UTC, chambo-e approved these changes

2022-10-24 09:15 UTC, matthprost requested changes

2022-10-24 09:15 UTC, matthprost commented on src/components/MarkDown/index.tsx
> +const MdHeading = ({
Possible to use full word instead of acronyms ?

```suggestion
const MarkDownHeading = ({
```

2022-10-24 13:42 UTC, chambo-e approved these changes

2022-10-24 13:48 UTC, matthprost approved these changes

2022-10-24 13:49 UTC, merged