refactor(BarChart,BarStack): rewrite stories
scaleway/scaleway-ui pull request #1987
Opened 2022-10-24 13:23 UTC by QuiiBz

## Summary

## Type

- Refactor

### Summarise concisely:

#### What is expected?

Rewrite stories for BarChart and BarStack. Badge was already done.

2022-10-24 13:28 UTC, matthprost requested changes

2022-10-24 13:28 UTC, matthprost commented on src/components/BarChart/__stories__/PositiveNegative.stories.tsx
> +export const PositiveNegative: ComponentStory<typeof BarChart> = () => (
Can you add props here to have more beautiful code snippet and remove those:

![Screenshot 2022-10-24 at 15 27 57](https://user-images.githubusercontent.com/15812968/197537149-157f4088-6c75-4276-98a3-8284e78148aa.png)

2022-10-24 13:29 UTC, matthprost requested changes

2022-10-24 13:29 UTC, matthprost commented on src/components/BarChart/__stories__/PositiveNegative.stories.tsx
> +export const PositiveNegative: ComponentStory<typeof BarChart> = () => (
Should be something like:

```ts
export const PositiveNegative: ComponentStory<typeof BarChart> = props => <BarChart {...props} otherProp={value} ... />
```

2022-10-24 16:16 UTC, matthprost approved these changes

2022-10-25 07:35 UTC, baptisteArno approved these changes
👌

2022-10-25 07:36 UTC, merged