refactor: reorganize and improve PieChart, Placeholder and SelectNumber stories
scaleway/scaleway-ui pull request #2019
Opened 2022-11-07 19:57 UTC by vincentaudebert

## Summary

## Type

- Refactor

### Summarise concisely:

#### What is expected?

reorganize and improve PieChart, Placeholder and SelectNumber stories

2022-11-08 09:02 UTC, matthprost requested changes

2022-11-08 09:04 UTC, baptisteArno commented on src/components/SelectNumber/__stories__/index.stories.tsx
> +          marginLeft: '2em',
My bad, that's a mistake

2022-11-08 09:09 UTC, vincentaudebert commented on src/components/SelectNumber/__stories__/index.stories.tsx
> +          marginLeft: '2em',
What's inside Menu stories?

2022-11-08 15:58 UTC, baptisteArno commented on src/components/PieChart/__stories__/Template.stories.tsx
> +)
```suggestion
export const Template: ComponentStory<typeof PieChart> = (props) => (
  <PieChart data={data} {...props} />
)
```

2022-11-08 15:58 UTC, baptisteArno commented on src/components/SelectNumber/__stories__/Template.stories.tsx
> +}
Template should be:

```tsx
export const Template: ComponentStory<typeof SelectNumber> = (props) => (
    <SelectNumber {...props} />
  )
```

2022-11-09 09:11 UTC, matthprost approved these changes

2022-11-09 10:22 UTC, baptisteArno approved these changes

2022-11-09 15:56 UTC, merged