fix: remove box list
scaleway/scaleway-ui pull request #2117
Opened 2022-12-12 08:38 UTC by vincentaudebert

## Summary

## Type

- Refactor

### Summarise concisely:

#### What is expected?

Removes box from list

2022-12-15 13:03 UTC, chambo-e commented on src/components/ActionBar/index.tsx
> +  align-items: center;
intended ?

2022-12-15 13:03 UTC, matthprost requested changes

2022-12-15 13:03 UTC, matthprost commented on src/components/List/index.tsx
> +  style?: React.CSSProperties
We don't do `React.XX` anymore, you can import `CSSProperties` directly

2022-12-15 13:09 UTC, vincentaudebert commented on src/components/ActionBar/index.tsx
> +  align-items: center;
yes select bar is broken otherwise :/

2022-12-15 13:20 UTC, vincentaudebert commented on src/components/ActionBar/index.tsx
> +  align-items: center;
good point. fixed

2022-12-19 16:18 UTC, chambo-e approved these changes

2022-12-19 17:43 UTC, philibea approved these changes

2022-12-20 08:47 UTC, matthprost approved these changes

2022-12-20 08:55 UTC, merged