fix(TextBox): show required icon with right components
scaleway/scaleway-ui pull request #2166
Opened 2023-01-03 14:51 UTC by QuiiBz

## Summary

## Type

- Bug

### Summarise concisely:

#### What is expected?

Allow having a required icon + a right component (randomize, password toggle...)

## Relevant logs and/or screenshots

New stories:

<img width="981" alt="Screenshot 2023-01-03 at 15 43 54" src="https://user-images.githubusercontent.com/43268759/210380959-f07217b0-ff76-441b-9892-dbaf1b041ee6.png">

Old ones not impacted:

<img width="995" alt="Screenshot 2023-01-03 at 15 44 04" src="https://user-images.githubusercontent.com/43268759/210381003-fff1f519-34a2-46fa-95e2-2a87076666ca.png">

2023-01-03 14:52 UTC, matthprost requested changes
Can you make them all with same width?

<img width="771" alt="Screenshot 2023-01-03 at 15 51 38" src="https://user-images.githubusercontent.com/15812968/210381370-e4f7aaaf-4fe5-4aa6-9a16-440f0a95b948.png">

2023-01-05 09:35 UTC, matthprost requested changes
<img width="991" alt="Screenshot 2023-01-05 at 10 34 03" src="https://user-images.githubusercontent.com/15812968/210747942-21d3d757-1588-41e6-bae3-25eb1ba436ec.png">

I was wondering what happen when you have required, randomize and unit. It seems like the right part is broken.

2023-01-05 10:23 UTC, QuiiBz commented
> I was wondering what happen when you have required, randomize and unit. It seems like the right part is broken.

Fixed, now we can have as many right components as we want.

2023-01-05 10:24 UTC, matthprost approved these changes

2023-01-05 13:29 UTC, chambo-e approved these changes

2023-01-05 13:55 UTC, merged