feat(Text): add `dir` prop
scaleway/scaleway-ui pull request #2219
Opened 2023-01-24 14:42 UTC by QuiiBz

## Summary

## Type

- Feature

### Summarise concisely:

#### What is expected?

Add a new `dir` prop to `<Text />` to change the direction of the text: https://developer.mozilla.org/fr/docs/Web/HTML/Global_attributes/dir

## Relevant logs and/or screenshots

<img width="709" alt="Screenshot 2023-01-24 at 15 38 24" src="https://user-images.githubusercontent.com/43268759/214324294-16e4c2d1-1526-4a0b-b475-af30f8cbeed4.png">

2023-01-24 14:44 UTC, matthprost requested changes

2023-01-24 14:44 UTC, matthprost commented on packages/ui/src/components/Text/index.tsx
> +  dir?: string
can't you use the type of `dir` from `p` or `div`?

2023-01-24 15:26 UTC, matthprost approved these changes

2023-01-25 09:30 UTC, BABAK0T0 approved these changes

2023-01-25 09:31 UTC, vincentaudebert commented
not sure to understand clearly what you mean by "the direction of the ... " ?

2023-01-25 09:33 UTC, QuiiBz commented
@vincentaudebert it's when you use the `oneLine` prop, the text is truncated with '...' at the end

2023-01-25 09:46 UTC, merged