fix(List): update List usages
scaleway/scaleway-ui pull request #2248
Opened 2023-02-06 17:33 UTC by fabienhebert

DRAFT

2023-02-08 10:32 UTC, matthprost requested changes
![Screenshot 2023-02-08 at 11 30 00](https://user-images.githubusercontent.com/15812968/217504558-7db7a81e-a22e-4efc-ac1d-4a7062576cda.png)

When `selectedIds={[]}` it leave global checkbox checked?

2023-02-08 10:39 UTC, matthprost requested changes

2023-02-08 10:39 UTC, matthprost commented on packages/ui/src/components/ListV2/ListRow.tsx
> +export const LIST_ROW_SENTIMENTS: Color[] = [
You can use `SENTIMENTS` variable from `packages/ui/src/theme/index.ts`

2023-02-08 16:26 UTC, matthprost commented
There quite a lot of new code not covered by unit testing might be nice to update tests too 😄

2023-02-13 15:16 UTC, fabienhebert commented on packages/ui/src/components/ListV2/ListHeaderRow.tsx
> +    return selectedIds.length === 0 ? false : 'indeterminate'
I get the point but It's sync with Checkbox `checked` prop, but keeping boolean for `checked` make sense. Ofc we can have a specific behavior here where a variable could be named `all | none | partial` and then convert this string value to the boolean or indeterminate but mb it sounds may be a bit overkill ? any opinion @matthprost ?

2023-02-13 17:16 UTC, matthprost approved these changes

2023-02-14 14:27 UTC, ModuloM commented on packages/ui/src/components/ListV2/ListRow.tsx
> +        aria-expanded={isRowExpanded}
Still need something for this?
If not, you can resolve ;)

2023-02-14 14:28 UTC, ModuloM approved these changes

2023-02-21 09:59 UTC, closed without merging