feat(components): add className and data-testid - Part 1
scaleway/scaleway-ui pull request #2363
Opened 2023-03-28 14:36 UTC by BABAK0T0

## Summary

## Type

- Enhancement

### Summarise concisely:

Add className and data-testid on every components

2023-03-29 15:30 UTC, matthprost requested changes

2023-03-29 15:30 UTC, matthprost commented on packages/ui/src/components/Bullet/index.tsx
>      <StyledContainer variant={variant} size={size} className={className}>
It should not be applied on tooltip but on the container instead:

```suggestion
  <Tooltip id={tooltipBaseId} text={tooltip}>
    <StyledContainer variant={variant} size={size} className={className} data-testid={dataTestId}>
```

2023-03-29 15:30 UTC, matthprost commented on packages/ui/src/components/Carousel/index.tsx
> +        data-testid="scrollbar-wrapper"
Why hardcoded value? Can't we add data-testid as prop and set it here?

2023-03-31 08:58 UTC, matthprost approved these changes

2023-03-31 09:00 UTC, QuiiBz approved these changes

2023-03-31 09:49 UTC, merged