feat(Link): add new `prominence` props
scaleway/scaleway-ui pull request #2403
Opened 2023-04-06 11:49 UTC by QuiiBz

## Summary

## Type

- Feature

### Summarise concisely:

#### What is expected?

Add a new `prominence` props to the `Link` component.

2023-04-06 12:40 UTC, matthprost requested changes

2023-04-06 13:54 UTC, QuiiBz commented on packages/ui/src/components/Link/index.tsx
> +    return theme.colors[variant]?.[text] ?? theme.colors.neutral.text
Done thanks @matthprost

2023-04-07 08:32 UTC, Lawndlwd approved these changes

2023-04-07 08:36 UTC, matthprost approved these changes

2023-04-07 08:38 UTC, merged