Feat/table v2
scaleway/scaleway-ui pull request #2468
Opened 2023-04-24 16:25 UTC by fabienhebert

## Summary

## Type

- Feature

### Summarise concisely:

Add a new component TableV2. The endgoal is to merge `Table (v1)`, `List (v1) variant table` & `List (v1) variant explorer` in this new component.

Table (V1) didn't supported ordering & selectable rows

2023-04-25 08:27 UTC, matthprost requested changes

2023-04-25 08:27 UTC, matthprost commented on packages/ui/src/components/ListV2/HeaderCell.tsx
> +                event.preventDefault()
I don't think we need the preventDefault 🤔

2023-04-25 08:27 UTC, matthprost commented on packages/ui/src/components/TableV2/HeaderCell.tsx
> +const HeaderCellContent = styled('div')`
Why not using a `Text` with prop `as="div"` so you don't need to add CSS related to text style

2023-04-25 08:27 UTC, matthprost commented on packages/ui/src/components/TableV2/HeaderCell.tsx
> +                event.preventDefault()
Same here I don't think we need preventDefault it should work without

2023-04-25 09:12 UTC, ModuloM commented on packages/ui/src/components/ListV2/HeaderCell.tsx
> +              if (event.key === ' ') {
Maybe we should also map `enter` key?
As we use this as a button (https://www.w3.org/WAI/ARIA/apg/patterns/button/)

2023-04-25 09:12 UTC, ModuloM commented on packages/ui/src/components/TableV2/HeaderCell.tsx
> +              if (event.key === ' ') {
Maybe we should also map enter key?

2023-04-28 13:46 UTC, ModuloM commented
Juste quick note on checkbox component, it doesn't listen to keydown `Enter` to change it's state (but not related to TableV2) 🚀

2023-05-03 08:28 UTC, matthprost commented
> Juste quick note on checkbox component, it doesn't listen to keydown `Enter` to change it's state (but not related to TableV2) 🚀

@ModuloM This might seems strange but for changing state with accessibility you should use space bar instead of enter. If you check on native checkbox that's how you change it and enter doesn't work 😛

2023-05-03 08:35 UTC, matthprost approved these changes

2023-05-03 08:35 UTC, matthprost commented on packages/ui/src/components/ListV2/HeaderCell.tsx
> +              if (event.key === ' ' || event.key === 'Enter') {
```suggestion
              if (event.key === ' ') {
```

2023-05-03 08:35 UTC, matthprost commented on packages/ui/src/components/TableV2/HeaderCell.tsx
> +              if (event.key === ' ' || event.key === 'Enter') {
```suggestion
              if (event.key === ' ') {
```
![Screenshot 2023-05-03 at 10 32 43](https://user-images.githubusercontent.com/15812968/235867646-c28b297e-be37-4e75-a84f-932bd40eb1da.png)

Here is a nice tool to get the value of each keys: https://www.toptal.com/developers/keycode

2023-05-03 08:35 UTC, matthprost commented on packages/ui/src/components/TableV2/__stories__/Style.stories.tsx
> +      <Stack gap={1}>
A key is missing

2023-05-03 09:52 UTC, merged