fix: use ButtonV2
scaleway/scaleway-ui pull request #2547
Opened 2023-05-22 12:40 UTC by fabienhebert

## Summary

## Type

- Enhancement
- Refactor

### Summarise concisely:

use ButtonV2 in scw-ui instead of Button (v1)
Remove Button(V1)
Rename ButtonV2 to Button

2023-05-22 13:48 UTC, matthprost requested changes

2023-05-22 13:48 UTC, matthprost commented on packages/ui/src/__stories__/ButtonMigration/Variants.tsx
> +import ButtonMigrationImg from '../assets/button-migration.png'
The migration page on storybook doesn't seems to work anymore, I have a white page

2023-05-22 13:48 UTC, matthprost commented on packages/ui/src/components/Menu/__stories__/Template.stories.tsx
> +  <Button icon="dots-horizontal" variant="ghost" size="medium" />
```suggestion
  <Button icon="dots-horizontal" variant="ghost" size="small" />
```

Old disclosure button was 32x32, so it should be small size

2023-05-22 13:48 UTC, matthprost commented on packages/ui/src/components/Modal/index.tsx
> +                    tooltip="close"
As we have `aria-label` we do not need tooltip here. Previous title was used for a11y, screen reader will be capable of reading the `aria-label`

2023-05-22 15:45 UTC, matthprost approved these changes

2023-05-23 08:46 UTC, BABAK0T0 approved these changes

2023-05-23 09:36 UTC, merged