fix: fix the number type input arrow position
scaleway/scaleway-ui pull request #2572
Opened 2023-05-29 13:02 UTC by Lawndlwd

## Summary

## Type

- Bug

#### What is expected?

fix the number type input arrow position

2023-05-29 13:10 UTC, QuiiBz approved these changes

2023-05-30 08:12 UTC, Lawndlwd commented on packages/ui/src/components/TextInput/index.tsx
> -    padding-right: ${rightElementPadding || 32}px;
mmm yes that's right

2023-05-30 08:49 UTC, matthprost requested changes

2023-05-30 08:49 UTC, matthprost commented on packages/ui/src/components/TextInput/index.tsx
> +    padding-right: ${rightElementPadding || theme.space[6]}px;
```suggestion
    padding-right: ${rightElementPadding || theme.space['6']}px;
```

2023-05-30 08:56 UTC, vincentaudebert approved these changes

2023-05-30 09:33 UTC, ModuloM approved these changes

2023-05-30 14:43 UTC, merged