fix(Menu): style
scaleway/scaleway-ui pull request #2586
Opened 2023-05-31 15:04 UTC by fabienhebert

## Summary

## Type

- Enhancement

### Summarise concisely:

Update Menu.Item style

2023-06-01 08:22 UTC, matthprost approved these changes

2023-06-01 16:11 UTC, matthprost commented on packages/ui/src/components/Menu/Item.tsx
> +  text-decoration: none;
Possible to add this:

```suggestion
  text-decoration: none;
  
  &:focus {
    text-decoration: none;
  }
```

2023-06-02 08:08 UTC, QuiiBz approved these changes

2023-06-02 08:36 UTC, matthprost requested changes
cf my comment ⬆️

2023-06-05 09:45 UTC, vincentaudebert approved these changes

2023-06-05 10:14 UTC, merged