refactor(TagList): use Popover component instead of Tooltip
scaleway/scaleway-ui pull request #2608
Opened 2023-06-08 09:32 UTC by QuiiBz

## Summary

## Type

- Refactor

### Summarise concisely:

#### The following changes where made:

- Use a `Popover` instead of a `Tooltip` for the threshold
- Add a new required `popoverTitle` prop
- Set `Popover` title to `bodyStrong` instead of `headerSmall`

## Relevant logs and/or screenshots

| Page |   Before   |      After |
| :--- | :--------: | ---------: |
| url  | <img width="186" alt="Screenshot 2023-06-08 at 11 29 47" src="https://github.com/scaleway/scaleway-ui/assets/43268759/facf2dda-9d1f-4d0b-ac5d-bf444a0d6376"> | <img width="550" alt="Screenshot 2023-06-08 at 11 30 11" src="https://github.com/scaleway/scaleway-ui/assets/43268759/c1198b15-f1af-4211-8e6f-fc21784e48d2"> |
| url  | <img width="935" alt="Screenshot 2023-06-08 at 11 30 32" src="https://github.com/scaleway/scaleway-ui/assets/43268759/ceaaa7f9-f74c-4a02-9f67-794d1ae6cd00"> | <img width="616" alt="Screenshot 2023-06-08 at 11 30 52" src="https://github.com/scaleway/scaleway-ui/assets/43268759/bd9483af-440c-47fd-97cc-91adf6d76452"> |

Custom Popover content:

<img width="473" alt="Screenshot 2023-06-08 at 11 31 29" src="https://github.com/scaleway/scaleway-ui/assets/43268759/19e486fb-15e7-462f-966f-b72b07625a0f">

2023-06-08 15:09 UTC, ModuloM approved these changes

2023-06-12 08:27 UTC, matthprost requested changes

2023-06-12 08:27 UTC, matthprost commented on packages/ui/src/components/TagList/index.tsx
> +          onClose={() => setIsVisible(false)}
You need to add a test on closing the popover

2023-06-12 08:27 UTC, matthprost commented on packages/ui/src/components/TagList/index.tsx
> +          <StyledTooltipReference onClick={() => setIsVisible(true)}>
Can we rename it differently as we do not use tooltip anymore?

2023-06-12 08:27 UTC, matthprost commented on packages/ui/src/components/TagList/index.tsx
> +          <StyledTooltipReference onClick={() => setIsVisible(true)}>
Also this line needs to be tested in unit testing

2023-06-13 09:30 UTC, matthprost requested changes

2023-06-13 09:30 UTC, matthprost commented on packages/ui/src/components/TagList/index.tsx
> +  children?: ({ tags }: { tags: string[] }) => ReactNode
to remove

2023-06-13 09:44 UTC, matthprost requested changes

2023-06-13 09:44 UTC, matthprost commented on packages/ui/src/components/TagList/index.tsx
> +   * This propery define the title of the Popover, when some tags are hidden because of the threshold.
```suggestion
   * This property define the title of the Popover, when some tags are hidden because of the threshold.
```

2023-06-13 09:46 UTC, matthprost approved these changes

2023-06-14 08:37 UTC, PetmePant approved these changes

2023-06-14 09:01 UTC, merged