feat(illustrations): first release
scaleway/scaleway-ui pull request #3007
Opened 2023-10-09 15:31 UTC by fabienhebert

## Summary

## Type

- Feature

### Summarise concisely:

Create a new "illustration" package with some product illustrations to begin with

### Usage

```ts
import { cockpitOriginal } from "@ultraviolet/illustrations/products/cockpit"
...
<img src={cockpitOriginal} />
```

## Relevant logs and/or screenshots

![Capture d’écran 2023-10-09 à 17 30 20](https://github.com/scaleway/ultraviolet/assets/8116991/d245cc4f-1060-423f-9a94-864fa68f52fd)

2023-10-09 15:34 UTC, matthprost requested changes
In the file `codecov.yml` can you add `packages/illustrations`? so we don't have the code coverage counted on those files

2023-10-09 15:34 UTC, matthprost commented on packages/illustrations/.jest/helpers.tsx
> +} = makeHelpers(Wrapper, { classNameReplacer: className => className })
I don't think we need this helper as the library doesn't need unit testing

2023-10-09 15:36 UTC, matthprost requested changes

2023-10-09 15:36 UTC, matthprost commented on packages/illustrations/src/index.ts
> +  products,
I don't know if you saw but the ticket got new comment in the structure, we need to have `product.instance`, `product.database` etc

2023-10-16 12:15 UTC, matthprost requested changes

2023-10-16 12:15 UTC, matthprost commented on codecov.yml
> +  - 'package/illustrations'
```suggestion
  - 'packages/illustrations'
```

2023-10-16 12:31 UTC, matthprost approved these changes

2023-10-16 15:21 UTC, JulienSaguez approved these changes

2023-10-19 14:22 UTC, merged