fix: CreationProgress errors
scaleway/scaleway-ui pull request #301
Opened 2021-04-30 13:20 UTC by DorianMaliszewski

## Summary

This Component is not used widely in our console at this time.

## What I did

- isStepNumber is not a valid prop name, replaced by variant prop
- When the CreationProgress is animated or not there are a misunderstanding of what is the current step

You can check on the creation progress page in the sizes section by switching variant and animated

## Screenshots

| Before        | After           | 
|:-------------:|:-------------:|
|  <img width="350" alt="Capture d’écran 2021-04-30 à 15 18 27" src="https://user-images.githubusercontent.com/24531136/116700669-54ba1780-a9c7-11eb-84a8-c52da1dc131e.png"> | <img width="349" alt="Capture d’écran 2021-04-30 à 15 19 11" src="https://user-images.githubusercontent.com/24531136/116700763-6dc2c880-a9c7-11eb-8112-5a32a5c7d692.png"> |

2021-05-03 13:16 UTC, matthprost requested changes

2021-05-03 13:16 UTC, matthprost commented on src/components/CreationProgress/__stories__/index.stories.mdx
> +  <Story name="numbered">
```suggestion
  <Story name="Numbered">
```

2021-05-03 13:16 UTC, matthprost commented on src/components/CreationProgress/index.js
> +            }
Seems like you are making condition to render exact same component with same properties

2021-06-28 12:51 UTC, DorianMaliszewski commented
Not to be done in the future, not a priority today

2021-06-28 12:51 UTC, closed without merging