feat: port RichSelectTags
scaleway/scaleway-ui pull request #323
Opened 2021-05-08 23:37 UTC by chambo-e

## Summary

## Type

- Migration

### Summarise concisely:

I kinda struggled to have 100% coverage, I don't know why it does not want to include the deletion while the test is executed

#### What is expected?

<img width="1072" alt="Screenshot 2021-05-09 at 01 35 56" src="https://user-images.githubusercontent.com/2802867/117556234-fa742300-b066-11eb-926d-10f254625499.png">
<img width="1046" alt="Screenshot 2021-05-09 at 01 35 59" src="https://user-images.githubusercontent.com/2802867/117556236-fba55000-b066-11eb-8f91-9bf60b0a0270.png">

2021-05-10 08:28 UTC, vincentaudebert approved these changes

2021-05-10 12:16 UTC, matthprost requested changes

2021-05-10 12:16 UTC, matthprost commented on src/components/RichSelectTags/index.js
> +      onChange(e)
In your tests onChange has empty paramters, tests are not passing trough those 2 lines

2021-05-10 12:16 UTC, matthprost commented on src/components/RichSelectTags/__stories__/index.stories.mdx
> +  <Story name="basic">
```suggestion
  <Story name="Basic">
```

2021-05-10 12:16 UTC, matthprost commented on src/components/RichSelectTags/index.js
> +        variant="bordered"
`RichSelect` and `Tags` have name as required prop, you can add a name to propTypes of `RichSelectTags` as required and add it in both components with prefix such as `name={"richselect-${name}"}` and `name={"tags-${name}"}`

2021-05-10 12:16 UTC, matthprost commented on src/components/RichSelectTags/index.js
> +  placeholder: PropTypes.string.isRequired,
Is there a reason to put placeholder as required ? Maybe we could give it a default value

2021-05-10 12:16 UTC, matthprost commented on src/components/RichSelectTags/index.js
> +  ctaText: PropTypes.string.isRequired,
Same for this prop, it could have a default value I think

2021-05-11 12:02 UTC, matthprost commented on src/components/RichSelectTags/index.js
> +      onChange(e)
mmh that's strange 🤔

2021-05-11 12:10 UTC, matthprost requested changes

2021-05-11 12:10 UTC, matthprost commented on src/components/RichSelectTags/__stories__/index.stories.mdx
> +  <Story name="Basic">
```suggestion
  <Story name="Basic" height="300px">
```

will avoid options hide under story:

<img width="1044" alt="Screenshot 2021-05-11 at 14 04 50" src="https://user-images.githubusercontent.com/15812968/117812335-f8c27f00-b261-11eb-82b7-098b832e091d.png">

2021-05-11 14:09 UTC, matthprost approved these changes

2021-05-12 14:08 UTC, merged