feat(icons): add export to IconName props
scaleway/scaleway-ui pull request #3426
Opened 2024-02-08 12:24 UTC by Slashgear

## Summary

## Type

- Feature

### Summarise concisely:

We need to get the IconName easily for wrapping purpose, extract this props from the component props is quite complex due to forwardRef, having it directly extracted would be really useful

#### The following changes where made:

(Describe what you did)

1. Add missing export type in package ultraviolet/icon

2024-02-08 15:59 UTC, matthprost requested changes
We don't usually export type that are already available through props, why not using this instead?

```ts
ComponentProps<typeof Icon>['name']
```

You will get the exact same type as `IconName`

2024-02-08 23:52 UTC, philibea commented
> > We don't usually export type that are already available through props, why not using this instead?
> > ```ts
> > ComponentProps<typeof Icon>['name']
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > You will get the exact same type as `IconName`
> > Edit: I've re-read your message, what's the issue with the forwardRef and componentProps?
> 
> Sadly due to `forwardRef` usage, this does not work 😢

You can do this one in this case :)
```ts
type IconName =  ComponentPropsWithoutRef<typeof Icon>['name']
```

2024-02-09 08:47 UTC, Slashgear commented
> > > We don't usually export type that are already available through props, why not using this instead?
> > > ```ts
> > > ComponentProps<typeof Icon>['name']
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > You will get the exact same type as `IconName`
> > > Edit: I've re-read your message, what's the issue with the forwardRef and componentProps?
> > 
> > 
> > Sadly due to `forwardRef` usage, this does not work 😢
> 
> You can do this one in this case :)
> 
> ```ts
> type IconName =  ComponentPropsWithoutRef<typeof Icon>['name']
> ```

We will try it, we already did and it did not work but let's retry it

2024-02-09 09:27 UTC, dcerbah commented
I tested the suggestion and it doesn't work, here is a screen of the error :

<img width="1305" alt="Capture d’écran 2024-02-09 à 09 54 23" src="https://github.com/scaleway/ultraviolet/assets/126498122/186e04b6-6fe7-4f87-a45e-a6e2f6585d64">

2024-02-09 10:51 UTC, matthprost commented
> I tested the suggestion and it doesn't work, here is a screen of the error :
> 
> <img alt="Capture d’écran 2024-02-09 à 09 54 23" width="1305" src="https://private-user-images.githubusercontent.com/126498122/303606338-186e04b6-6fe7-4f87-a45e-a6e2f6585d64.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0NzI5ODAsIm5iZiI6MTcwNzQ3MjY4MCwicGF0aCI6Ii8xMjY0OTgxMjIvMzAzNjA2MzM4LTE4NmUwNGI2LTZmZTctNGY4Ny1hNDVlLWE2ZTJmNjU4NWQ2NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwOVQwOTU4MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MTRjYTdiZGVkYzFlYmJhOGQ4ZGViYWJhOGU4YzVkZDY2MmY0MmQxYmQ3OWZhYzdmMGY0ZDc1NzRkYzJjM2NiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UUEMDQYYQHHJ0Wr-KOkl9wj8_3Fzc50C6LlGd4DyRPs">

I tried locally on another project than ultraviolet, it seems to work just fine:
<img width="532" alt="Screenshot 2024-02-09 at 11 45 49" src="https://github.com/scaleway/ultraviolet/assets/15812968/0c748a84-8aea-4e45-a94e-06978be5a4a0">

Is there any ways you could provide me a way to reproduce or try this error locally? So I can help you search for a solution.

2024-02-16 10:08 UTC, dcerbah commented
Following your investigations this problem came from our yarn lock file, thanks for your help.

2024-02-16 10:08 UTC, closed without merging