refactor: toaster update
scaleway/scaleway-ui pull request #3441
Opened 2024-02-12 10:09 UTC by lisalupi

## Summary

## Type

- Refactor

### Summarise concisely:

#### What is expected?

Updated Toaster

#### The following changes where made:

(Describe what you did)

1. New colors for the sentiments

2. New sentiment ("warning")

3. When multiple toasters : stacked

4. No more progress bar 

## Relevant logs and/or screenshots

| Page |   Before   |      After |
| :---: | :--------: | :---------: |
| Success  | <img width="328" alt="sucess before" src="https://github.com/scaleway/ultraviolet/assets/106706307/6ffa811f-8d2e-478e-8488-e7140a21f649"> | <img width="354" alt="Capture d’écran 2024-02-13 à 09 49 38" src="https://github.com/scaleway/ultraviolet/assets/106706307/a0215052-3cda-4d55-8834-e75755ca633f"> |
| Info (deprecated)  | <img width="331" alt="Capture d’écran 2024-02-12 à 10 56 52" src="https://github.com/scaleway/ultraviolet/assets/106706307/c965d213-dbba-4ecf-a728-2605d3064691"> | <img width="351" alt="Capture d’écran 2024-02-13 à 09 49 45" src="https://github.com/scaleway/ultraviolet/assets/106706307/88550b5f-48e0-437e-b975-f367749fdf9e"> |
| Error | <img width="320" alt="Capture d’écran 2024-02-12 à 10 59 49" src="https://github.com/scaleway/ultraviolet/assets/106706307/7a02f042-7f52-4f21-9e56-959113a3c1a8">| <img width="352" alt="Capture d’écran 2024-02-13 à 09 49 52" src="https://github.com/scaleway/ultraviolet/assets/106706307/6e2384eb-3abc-4760-b108-aa388cd71956"> |
| Warning | / | <img width="350" alt="Capture d’écran 2024-02-13 à 09 49 59" src="https://github.com/scaleway/ultraviolet/assets/106706307/6d336f74-9eae-44bc-90d7-33aafe6f4da4">|

2024-02-12 12:31 UTC, matthprost requested changes

2024-02-12 12:31 UTC, matthprost commented on packages/ui/src/components/Toaster/index.tsx
>      <Icon name={TOAST_ICONS[sentiment]} size={24} />
You can remove this icon we don't have it anymore in the proto of design

<img width="358" alt="Screenshot 2024-02-12 at 13 29 10" src="https://github.com/scaleway/ultraviolet/assets/15812968/57cf7c91-e73e-4b8b-bd0e-22cd117caeea">

2024-02-12 12:32 UTC, matthprost requested changes
You can try to align vertically the close button on toaster to be aligned with design specifications.

Yours:
<img width="305" alt="Screenshot 2024-02-12 at 13 31 27" src="https://github.com/scaleway/ultraviolet/assets/15812968/45973b1f-30b0-46c2-9d5a-966419d1be3f">

Design:
<img width="356" alt="Screenshot 2024-02-12 at 13 31 21" src="https://github.com/scaleway/ultraviolet/assets/15812968/4f982e11-8735-4211-883f-39a8a7e1016c">

2024-02-12 12:40 UTC, matthprost commented
> ### ⚠️ No Changeset found
> Latest commit: [1eb4fca](https://github.com/scaleway/ultraviolet/commit/1eb4fca7bed9e6558d05d762c4cbf378db3556d8)
> 
> Merging this PR will not cause a version bump for any packages. If these changes should not result in a new version, you're good to go. **If these changes should result in a version bump, you need to add a changeset.**
> 
> This PR includes no changesets
> [Click here to learn what changesets are, and how to add one](https://github.com/changesets/changesets/blob/main/docs/adding-a-changeset.md).
> 
> [Click here if you're a maintainer who wants to add a changeset to this PR](https://github.com/scaleway/ultraviolet/new/refactor/toaster?filename=.changeset/few-cows-refuse.md&value=---%0A%22%40ultraviolet%2Fui%22%3A%20patch%0A---%0A%0Arefactor%3A%20toaster%20update%0A)

The changeset is missing here also 😄

2024-02-12 16:39 UTC, matthprost requested changes

2024-02-12 16:39 UTC, matthprost commented on packages/ui/src/components/Toaster/index.tsx
> +    padding: 16px 16px 16px 16px;
for the padding you can use:

```suggestion
    padding: ${theme.space['2']};
```

2024-02-12 16:39 UTC, matthprost commented on packages/ui/src/components/Toaster/index.tsx
> +    gap: 16px;
The gap here won't work cause you don't have a display flex, you can remove it

```suggestion
```

2024-02-12 16:39 UTC, matthprost commented
> ### ⚠️ No Changeset found
> Latest commit: [0ceea28](https://github.com/scaleway/ultraviolet/commit/0ceea2865751c0437097a00578c00fee4374a9db)
> 
> Merging this PR will not cause a version bump for any packages. If these changes should not result in a new version, you're good to go. **If these changes should result in a version bump, you need to add a changeset.**
> 
> This PR includes no changesets
> [Click here to learn what changesets are, and how to add one](https://github.com/changesets/changesets/blob/main/docs/adding-a-changeset.md).
> 
> [Click here if you're a maintainer who wants to add a changeset to this PR](https://github.com/scaleway/ultraviolet/new/refactor/toaster?filename=.changeset/cyan-readers-care.md&value=---%0A%22%40ultraviolet%2Fui%22%3A%20patch%0A---%0A%0Arefactor%3A%20toaster%20update%0A)

Changeset is still missing 😄

2024-02-12 17:07 UTC, PetmePant requested changes
- Text should be changed to bodySmallStrong
- Close icon seems not to have button states 
- Not sure that the location is clear, bottom-right

2024-02-14 12:51 UTC, matthprost requested changes

2024-02-14 14:58 UTC, fabienhebert approved these changes

2024-02-15 09:19 UTC, mhervouet commented
When you hover the toaster pile, it must open from bottom to top (like in the video)

https://github.com/scaleway/ultraviolet/assets/145689179/72d839ac-a5bb-4351-a7f2-05ca5b9b4b5a

2024-02-15 16:34 UTC, matthprost approved these changes

2024-02-15 16:41 UTC, mhervouet approved these changes

2024-02-15 16:42 UTC, merged