fix: rich select issues
scaleway/scaleway-ui pull request #372
Opened 2021-05-24 07:58 UTC by DorianMaliszewski

## Summary

## Type

- Bug

### Summarise concisely:

#### What is expected?

- When in multi mode, select doesn't display the label
- When isSearchable, select display an input which is not vertical aligned
- When selecting an option, select doesn't keep the scroll (documented)
- When disabled, select doesn't display the label

#### The following changes where made:

1. Lot of changes in RichSelect styles and props

2. UnitInput test wasn't good so fix it and comment

3. Add isSearchable story

2021-05-24 08:16 UTC, chambo-e commented on src/components/UnitInput/__tests__/index.js
> +  test.only(`renders with RichSelect update`, async () => {
💩

2021-05-24 08:22 UTC, matthprost requested changes
Searcheable test is hovering label a bit:

https://user-images.githubusercontent.com/15812968/119318614-d2e1a500-bc79-11eb-9585-2b0af1485535.mov

2021-05-24 08:27 UTC, DorianMaliszewski commented on src/components/UnitInput/__tests__/index.js
> +  test.only(`renders with RichSelect update`, async () => {
Oups

2021-05-25 12:54 UTC, chambo-e requested changes

2021-05-25 12:54 UTC, chambo-e commented on package.json
> +      "html"
Useless noise no ? We can add the reporter whenever we want with the cli

2021-05-25 12:54 UTC, chambo-e commented on src/components/RichSelect/__tests__/index.js
>    })
```suggestion
  test('renders correctly uncontrolled', () => (
    shouldMatchEmotionSnapshot(
      <RichSelect inputId="test" labelId="test-label" name="uncontrolled">
        <RichSelect.Option value="a">Option A</RichSelect.Option>
        <RichSelect.Option value="b">Option B</RichSelect.Option>
      </RichSelect>,
      {
        transform: async node => {
          const input = node.getByRole('textbox')
          userEvent.click(input)
        },
      },
    )
  ))
```

2021-05-25 15:31 UTC, matthprost requested changes

2021-05-25 15:31 UTC, matthprost commented on src/components/Tags/index.js
> +            key={`${tag.index}`}
```suggestion
            key={tag.index}
```

2021-05-27 07:06 UTC, matthprost approved these changes

2021-05-27 09:33 UTC, vincentaudebert commented on src/components/Tags/index.js
> +            key={`${tag.index}`}
FYI, j'ai rajoute le label dans ma MR car le UUID est pas unique pour tous les tags

2021-05-27 09:35 UTC, vincentaudebert commented
<img width="1036" alt="Screenshot 2021-05-27 at 11 35 15" src="https://user-images.githubusercontent.com/3360430/119803305-9f07b900-bedf-11eb-97c9-e6f715ebeb2b.png">


Design suggestion but should we align center when searching?

2021-05-27 12:27 UTC, DorianMaliszewski commented on src/components/Tags/index.js
> +            key={`${tag.index}`}
Je peux quand même laisser où ca te derange ?

2021-05-27 12:50 UTC, vincentaudebert commented on src/components/Tags/index.js
> +            key={`${tag.index}`}
nah all good cetait juste pour info :)

2021-05-27 12:59 UTC, chambo-e commented on src/components/RichSelect/__tests__/index.js
>    })
You need to return the shouldMatchEmotionSnapshot for the await to be triggered

2021-05-27 13:02 UTC, chambo-e commented on src/components/Tags/index.js
> +            key={tag.index}
This is too much conflict prone no ?

2021-05-27 13:16 UTC, DorianMaliszewski commented on src/components/Tags/index.js
> +            key={tag.index}
This key is randomly generated

2021-05-27 13:25 UTC, chambo-e approved these changes

2021-05-27 13:29 UTC, merged