docs: improves documentation for components from l to n CNS-3985
scaleway/scaleway-ui pull request #386
Opened 2021-05-27 14:11 UTC by vincentaudebert

## Summary

## Type

- Documentation

### Summarise concisely:

#### What is expected?

Documentation for L and N components

#### The following changes where made:

    Label
    Link
    MarkDown
    MenuIcon
    Modal
    Notice
    NotificationBar

2021-05-28 13:08 UTC, chambo-e requested changes

2021-05-28 13:08 UTC, chambo-e commented on src/components/Modal/__stories__/helpers.js
> +export const animations = [
I think that you can export all these const from the component, there is going to be a discrepancy as some point if we go this way :)

2021-05-31 07:50 UTC, matthprost requested changes
Before any `<ArgsTable>` can you add  `## API` title ?

2021-05-31 07:52 UTC, matthprost requested changes

2021-05-31 07:52 UTC, matthprost commented on src/components/MarkDown/__stories__/index.stories.mdx
> +  <Story name="With paragraphs inline">
Can we change it for `Paragraphs` and remove the `with`

2021-05-31 08:13 UTC, matthprost commented
![Screenshot 2021-05-31 at 10 13 13](https://user-images.githubusercontent.com/15812968/120162588-d5537a00-c1f8-11eb-961d-f1331170148c.png)

No example for link component ?

2021-05-31 08:15 UTC, matthprost requested changes

2021-05-31 08:15 UTC, matthprost commented on src/components/MarkDown/__stories__/index.stories.mdx
> +
Both properties `linkTarget` and `escapeHtml ` are missing in examples and no comments on them so we don't know what they can be used for

2021-05-31 08:17 UTC, matthprost requested changes

2021-05-31 08:17 UTC, matthprost commented on src/components/MenuIcon/__stories__/index.stories.mdx
> +  <Story name="Basic">
Many properties missing in examples such as `color`, `size` and `isButton`

2021-05-31 12:40 UTC, chambo-e approved these changes

2021-06-01 10:16 UTC, matthprost approved these changes

2021-06-01 10:19 UTC, merged