docs: updated all C components doc
scaleway/scaleway-ui pull request #387
Opened 2021-05-27 15:49 UTC by matthprost

## Summary

## Type

- Documentation

### Summarise concisely:

#### What is expected?

To have better documentation for all starting C letter components.

⚠️ CreationProgress not include as full refacto is needed ⚠️ 

#### The following changes where made:

1. Updated stories

2. Fixed checkbox when progress is true not to be clickable

2021-05-28 13:09 UTC, chambo-e commented on src/components/Checkbox/index.js
> +          onChange={e => {
Maybe add a test for this use case ?

2021-05-31 11:08 UTC, DorianMaliszewski requested changes
Differences between sidebar and story order/name

2021-06-01 09:55 UTC, DorianMaliszewski commented
<img width="1713" alt="Capture d’écran 2021-06-01 à 11 54 53" src="https://user-images.githubusercontent.com/24531136/120304570-313d0200-c2d0-11eb-9b24-85ef7e0bdd11.png">
Still there

2021-06-01 09:58 UTC, DorianMaliszewski requested changes
See comments

2021-06-01 10:24 UTC, matthprost commented
> <img alt="Capture d’écran 2021-06-01 à 11 54 53" width="1713" src="https://user-images.githubusercontent.com/24531136/120304570-313d0200-c2d0-11eb-9b24-85ef7e0bdd11.png">
> 
> Still there

<img width="1910" alt="Screenshot 2021-06-01 at 12 24 01" src="https://user-images.githubusercontent.com/15812968/120308322-46b42b00-c2d4-11eb-9fd6-068aec0fbec1.png">

I think you may have cache

2021-06-01 13:59 UTC, DorianMaliszewski commented
When clearing the cache and go to the chart it's still there. What did you have @chambo-e ?

2021-06-01 15:50 UTC, chambo-e approved these changes

2021-06-02 15:33 UTC, DorianMaliszewski approved these changes

2021-06-02 15:45 UTC, merged