feat: add FlexBox component
scaleway/scaleway-ui pull request #391
Opened 2021-05-30 21:32 UTC by chambo-e

## Summary

This will allow us to remove loads of `<Box display="flex"`, we currently have ~200

This component does not inherits xstyled props, so it should only be used to replace "pure" flex Box for now

We need to have a way to handle spacing (p and m) and we should be able to replace all xstyled usage

## Type

- Feature

2021-05-31 11:03 UTC, DorianMaliszewski requested changes

2021-05-31 11:03 UTC, DorianMaliszewski commented on src/components/FlexBox/__stories__/index.stories.mdx
> +  <Story name="Container">
Basic is the first story name 😄

2021-05-31 11:05 UTC, DorianMaliszewski commented
<img width="1042" alt="Capture d’écran 2021-05-31 à 13 04 08" src="https://user-images.githubusercontent.com/24531136/120184004-c1b40d80-c210-11eb-9c3e-48693ddab592.png">
Is this normal ? And in the page the ArgsTables are empty IDK why ??

2021-05-31 12:29 UTC, chambo-e commented
> <img alt="Capture d’écran 2021-05-31 à 13 04 08" width="1042" src="https://user-images.githubusercontent.com/24531136/120184004-c1b40d80-c210-11eb-9c3e-48693ddab592.png">
> 
> Is this normal ? And in the page the ArgsTables are empty IDK why ??

@DorianMaliszewski what do you mean ? The `Show Code` button ?

2021-06-01 09:25 UTC, vincentaudebert commented
Any idea why we lose a bit of coverage on Toaster? 🤔

2021-06-01 09:29 UTC, vincentaudebert approved these changes

2021-06-01 09:52 UTC, DorianMaliszewski commented
> > <img alt="Capture d’écran 2021-05-31 à 13 04 08" width="1042" src="https://user-images.githubusercontent.com/24531136/120184004-c1b40d80-c210-11eb-9c3e-48693ddab592.png">
> > Is this normal ? And in the page the ArgsTables are empty IDK why ??
> 
> @DorianMaliszewski what do you mean ? The `Show Code` button ?

Yeah there a blank space below

2021-06-01 10:05 UTC, chambo-e commented
> Any idea why we lose a bit of coverage on Toaster? 🤔

@vincentaudebert I think it's a codecov error, if you go on the website they show no change on these files

2021-06-01 10:06 UTC, chambo-e commented
> > > <img alt="Capture d’écran 2021-05-31 à 13 04 08" width="1042" src="https://user-images.githubusercontent.com/24531136/120184004-c1b40d80-c210-11eb-9c3e-48693ddab592.png">
> > > Is this normal ? And in the page the ArgsTables are empty IDK why ??
> > 
> > 
> > @DorianMaliszewski what do you mean ? The `Show Code` button ?
> 
> Yeah there a blank space below

@DorianMaliszewski no idea, I don't have it 😄 

<img width="1052" alt="Screenshot 2021-06-01 at 12 06 18" src="https://user-images.githubusercontent.com/2802867/120306145-d73d3c00-c2d1-11eb-9342-001930e703a9.png">

2021-06-02 06:59 UTC, matthprost approved these changes

2021-06-17 11:39 UTC, merged