feat: merge Action into Button
scaleway/scaleway-ui pull request #437
Opened 2021-06-14 11:54 UTC by chambo-e

## Summary

## Type

- Refactor

### Summarise concisely:

```js
<Action name="lock" /> 
// =>
<Button action icon="lock" />
```
```js
<Action variant="rounded" /> 
// =>
<Button action="rounded" icon="lock" />
```

Also added tooltip support to Button

```js
<Button tootltip="I will be in a tooltip">Click Me</Button>
```

And iconSize
```js
<Button action="rounded" icon="lock" iconSize={32} />
```

2021-06-14 15:51 UTC, philibea approved these changes

2021-06-15 08:53 UTC, matthprost commented
I think it will be more simple if we just check if button contains only icon then we remove padding ? Cause now I see no difference between action and simple button icon. And for the rounded part it should be a variant

2021-06-15 08:53 UTC, matthprost requested changes
See up comment

2021-06-15 11:32 UTC, chambo-e commented
> I think it will be more simple if we just check that button contains only icon then we remove padding ? Cause now I see no difference between action and simple button icon. Plus, it create a prop that is meaningless :/
> For the rounded part it should be a variant.

For the rounded prop we can't use a variant because we could have a `rounded secondary` button for example

For the icon only button there will be an issue with existing component which only have an icon and need a padding :)

2021-06-15 13:58 UTC, matthprost requested changes

2021-06-15 13:58 UTC, matthprost commented on src/components/Button/index.js
>    icon: PropTypes.oneOfType([PropTypes.string, PropTypes.node, PropTypes.func]),
```suggestion
  icon: PropTypes.node,
```

2021-06-16 08:00 UTC, matthprost approved these changes

2021-06-17 11:09 UTC, merged