docs: add e and g documentation
scaleway/scaleway-ui pull request #459
Opened 2021-06-22 11:53 UTC by DorianMaliszewski

## Summary

## Type

- Documentation

### Summarise concisely:

#### What is expected?

Documentation on E and G components

#### The following changes where made:

1. Add documentation on proptypes

2. Update stories

## Relevant logs and/or screenshots
<img width="268" alt="Capture d’écran 2021-06-22 à 13 52 22" src="https://user-images.githubusercontent.com/24531136/122919915-1571cc80-d361-11eb-9ebc-53089bc93d8a.png">
<img width="684" alt="Capture d’écran 2021-06-22 à 13 52 59" src="https://user-images.githubusercontent.com/24531136/122919993-29b5c980-d361-11eb-8b66-c84b4e89427b.png">
<img width="257" alt="Capture d’écran 2021-06-22 à 13 53 18" src="https://user-images.githubusercontent.com/24531136/122920035-3508f500-d361-11eb-9353-e56fbdafdfa7.png">

2021-06-22 12:38 UTC, matthprost requested changes

2021-06-22 12:38 UTC, matthprost commented on src/components/ExtendedReminder/__stories__/index.stories.mdx
> +# Link
```suggestion
## Link
```

2021-06-23 14:08 UTC, chambo-e commented on src/components/Grid/Row.js
> +const Row = props => <StyledRow {...props} />
```suggestion
const Row = StyledRow
```

2021-06-23 14:09 UTC, chambo-e commented on src/components/Grid/Grid.js
> +const Grid = props => <StyledGrid {...props} />
```suggestion
const Grid = StyledGrid
```

2021-06-23 14:09 UTC, chambo-e commented on src/components/Grid/Col.js
> +const Col = props => <StyledCol {...props} />
```suggestion
const Col = StyledCol
```

2021-06-25 08:26 UTC, matthprost approved these changes

2021-06-25 12:45 UTC, chambo-e approved these changes

2021-06-25 13:22 UTC, merged