feat: d components
scaleway/scaleway-ui pull request #471
Opened 2021-06-28 13:36 UTC by DorianMaliszewski

## Summary

I put `feat` on the title to deply a new version because of merging icon, menuicon and categoryicon which was refactored (need to be implemented on our console)

## Type

- Documentation

### Summarise concisely:

#### What is expected?

Documentation on D components

2021-06-28 15:18 UTC, chambo-e approved these changes

2021-06-28 15:23 UTC, matthprost requested changes

2021-06-28 15:23 UTC, matthprost commented on src/components/DateInput/__stories__/index.stories.mdx
> +    <DateInput label="ru-RU" locale={ru} />
```suggestion
    <DateInput label="fr-FR" locale={fr} mb={3} />
    <DateInput label="es-ES" locale={es} mb={3} />
    <DateInput label="ru-RU" locale={ru} />
```

2021-06-28 15:23 UTC, matthprost commented on src/components/DateInput/index.js
> +   * `true` if this input need to be focused by default
It is a perturbing sentence, maybe `When this value is set to true the input will be focused by default`

2021-06-29 15:50 UTC, matthprost approved these changes

2021-06-30 09:28 UTC, merged