docs: r components
scaleway/scaleway-ui pull request #494
Opened 2021-07-01 08:56 UTC by DorianMaliszewski

## Summary

## Type

- Documentation

### Summarise concisely:

#### What is expected?

Documentation on R component. **No documentation on Range because this component is totally broken**

2021-07-01 10:40 UTC, matthprost requested changes

2021-07-01 10:40 UTC, matthprost commented on src/components/RadioBorderedBox/__stories__/index.stories.mdx
> +</Canvas>
Can we make it controlled component so they are no all checked ?

2021-07-01 10:40 UTC, matthprost commented
<img width="1054" alt="Screenshot 2021-07-01 at 12 37 38" src="https://user-images.githubusercontent.com/15812968/124111343-79834780-da69-11eb-9b13-9061ce52b5c0.png">

Its not part of migration but could you make text disabled too ?

2021-07-05 08:37 UTC, chambo-e approved these changes

2021-07-07 14:36 UTC, philibea approved these changes

2021-07-07 14:37 UTC, merged