docs(storybook): fixed argstable
scaleway/scaleway-ui pull request #532
Opened 2021-07-12 13:52 UTC by matthprost

## Summary

## Type

- Documentation

### Summarise concisely:

#### What is expected?

To be able to show prop of each components in storybook argstable.

#### The following changes where made:

1. Fixed all missing props in documentation

2021-07-22 09:14 UTC, DorianMaliszewski requested changes
<img width="1067" alt="Capture d’écran 2021-07-22 à 11 13 30" src="https://user-images.githubusercontent.com/24531136/126615894-381ad335-9be2-49b6-ace7-d457b318a56a.png">
<img width="1072" alt="Capture d’écran 2021-07-22 à 11 14 00" src="https://user-images.githubusercontent.com/24531136/126615936-79c01a6d-4348-463e-9784-8d45b819d51b.png">

Still this two components which doesn't work and it's good imo

2021-07-22 12:24 UTC, matthprost commented
> <img alt="Capture d’écran 2021-07-22 à 11 13 30" width="1067" src="https://user-images.githubusercontent.com/24531136/126615894-381ad335-9be2-49b6-ace7-d457b318a56a.png">
> 
> <img alt="Capture d’écran 2021-07-22 à 11 14 00" width="1072" src="https://user-images.githubusercontent.com/24531136/126615936-79c01a6d-4348-463e-9784-8d45b819d51b.png">
> 
> Still this two components which doesn't work and it's good imo

@DorianMaliszewski Its because they don't have any props, they are just a styled box without any entry prop

2021-07-26 15:36 UTC, chambo-e approved these changes

2021-07-27 13:27 UTC, DorianMaliszewski approved these changes

2021-07-27 13:35 UTC, merged