feat: start migration to typescript
scaleway/scaleway-ui pull request #589
Opened 2021-07-29 09:07 UTC by DorianMaliszewski

## Summary

## Type

- Migration

### Summarise concisely:

#### What is expected?

To typescript :

- ActionBar
- ActivityIndicator
- Typography
- Tooltip

#### The following changes where made:

1. Migrate proptypes to typescript interface and change defaultprops by function default param

2021-07-29 09:42 UTC, chambo-e requested changes

2021-07-29 09:42 UTC, chambo-e commented on .eslintrc
> +  "extends": ["@scaleway/react", "plugin:mdx/recommended", "airbnb-typescript"],
Already included in @scaleway/eslint-config/typescript :)

2021-07-29 09:42 UTC, chambo-e commented on src/theme/colors.ts
> +const colors: Record<string, string> = {
Why ? You shouldn't to change this file no ? Just change the extension and it should just work ? 🤔

2021-07-29 12:08 UTC, chambo-e commented on .eslintrc
> +        "react/require-default-props": "off",
Rather https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/require-default-props.md#ignorefunctionalcomponents :)

2021-07-30 08:44 UTC, chambo-e commented on src/components/Tooltip/index.tsx
> +  black: ({ theme }: { theme: SCWUITheme }) => css`
We should use Emotion.Theme here no ?

2021-07-30 08:53 UTC, chambo-e commented on src/components/Typography/__tests__/index.test.tsx
> +    ;(ReactDOM.createPortal as unknown as { mockClear: () => void }).mockClear()
```suggestion
    (ReactDOM.createPortal as jest.Mock).mockClear()
```

2021-07-30 08:53 UTC, DorianMaliszewski commented on src/components/Tooltip/index.tsx
> +  black: ({ theme }: { theme: SCWUITheme }) => css`
Ok :)

2021-07-30 09:40 UTC, matthprost requested changes

2021-07-30 09:40 UTC, matthprost commented on src/components/Typography/__tests__/index.test.tsx
> +    ({ children, ...props }: { children: (props: unknown) => unknown }) =>
What about `props: { [x: string]: unknown }` ? It's a bit same but at least it precise the structure

2021-07-30 09:40 UTC, matthprost commented on src/components/Typography/index.tsx
> +  maxLines?: string | number
`maxLine` is defined as a number everywhere else in this file

```suggestion
  maxLines?: number
```

2021-07-30 09:40 UTC, matthprost commented on src/components/Typography/index.tsx
> +  variant: PropTypes.oneOf(typographyVariants),
There is `width?: string | number` for type definition but the is none in propTypes

2021-08-02 10:30 UTC, matthprost requested changes

2021-08-02 10:30 UTC, matthprost commented on src/components/Typography/index.tsx
> +  as?: unknown
Can't it be a string type ?

2021-08-02 15:32 UTC, matthprost approved these changes

2021-08-02 15:34 UTC, chambo-e approved these changes

2021-08-02 15:41 UTC, merged