feat: migrate list tot ypescript
scaleway/scaleway-ui pull request #708
Opened 2021-09-07 13:57 UTC by DorianMaliszewski

## Summary

## Type

- Migration

### Summarise concisely:

#### What is expected?

Migrate List component to typescript (Need pagination First)

#### The following changes where made:

1. Migrate component

2. Migrate tests

2021-09-13 16:49 UTC, adriengibrat commented on src/components/List/__tests__/__snapshots__/index.test.tsx.snap
> +        as="div"
oops

2021-09-13 16:50 UTC, adriengibrat commented on src/components/List/__tests__/__snapshots__/index.test.tsx.snap
> +        as="div"
same, and multiple times below

2021-09-14 10:04 UTC, adriengibrat commented on src/components/List/__tests__/index.test.tsx
> +                const { rowData } = props as ListBodyRenderProps<ListRowData>
I tried to improve this (use type inference to avoid having typing `rowData`) but couldn't do better...

2021-09-14 10:08 UTC, adriengibrat requested changes

2021-09-14 10:08 UTC, adriengibrat commented on src/components/List/__tests__/__snapshots__/index.test.tsx.snap
> +        as="div"
In the snapshot some `details` becomes `div` & a few `div` becomes `details`

2021-09-15 10:56 UTC, DorianMaliszewski commented on src/components/List/SortIcon.tsx
> +  active,
This props will never be undefined 🤔

2021-09-15 13:37 UTC, matthprost approved these changes
Except that it's all good to me

2021-09-15 13:37 UTC, matthprost commented on src/components/List/SelectBar.tsx
> +      <Box display="flex" flex={1} justifyContent="flex-end">
Flexbox ?

2021-09-15 14:32 UTC, chambo-e commented on src/components/List/SortIcon.tsx
> +  active,
Well it might as it's optional no ?

2021-09-15 14:52 UTC, chambo-e approved these changes

2021-09-16 08:50 UTC, merged