refactor: migrate Reminder, RichSelect, ScrollView stories to tsx
scaleway/scaleway-ui pull request #877
Opened 2021-11-04 13:33 UTC by QuiiBz

## Summary

## Type

- Refactor

### Summarise concisely:

#### The following changes where made:

Migrate Reminder, RichSelect, ScrollView stories to tsx

2021-11-08 08:55 UTC, chambo-e requested changes

2021-11-08 08:55 UTC, chambo-e commented on src/components/ScrollView/__stories__/index.stories.tsx
> +  <ScrollView height="300px" {...args}>
As ScrollView does not accept xstyled props anymore it seems that this example is not working

Maybe ?
```suggestion
  <ScrollView style={{ height: "300px" }} {...args}>
```

2021-11-08 10:45 UTC, chambo-e commented on src/components/RichSelect/__stories__/index.stories.tsx
> +      <ControlValue value="">
```suggestion
      <ControlValue<string> value="">
```

To avoid eslint-disable below ?

2021-11-08 13:10 UTC, chambo-e approved these changes

2021-11-09 09:22 UTC, vincentaudebert commented on src/components/Reminder/__stories__/index.stories.tsx
> +    display="flex"
Do we really need display flex and mb 1 in the template?

2021-11-09 09:37 UTC, vincentaudebert approved these changes

2021-11-09 09:37 UTC, vincentaudebert commented on src/components/Reminder/__stories__/index.stories.tsx
> +    display="flex"
Just tried and display flex and mb 1 can be removed from here.

2021-11-09 10:18 UTC, merged