refactor(theme): colors migration Button, Breadcrumbs, BulletList…
scaleway/scaleway-ui pull request #982
Opened 2021-12-09 14:56 UTC by matthprost

## Summary

## Type

- Refactor

### Summarise concisely:

#### What is expected?

Migrated:

- Button
- Breadcumbs
- BulletList
- Checkbox

2021-12-13 08:40 UTC, adriengibrat approved these changes

2021-12-13 09:44 UTC, vincentaudebert commented on src/components/Checkbox/index.tsx
> +  color: ${({ theme }) => theme.colors.danger.backgroundStrong};
C'est pas un background ici si?

2021-12-13 09:47 UTC, vincentaudebert requested changes
cf mes comments

2021-12-13 09:47 UTC, vincentaudebert commented on src/components/Breadcrumbs/index.tsx
> +  color: ${({ theme }) => theme.colors.neutral.backgroundWeak};
Idem ici c'est pas un background?

2021-12-13 10:04 UTC, matthprost commented on src/components/Checkbox/index.tsx
> +  color: ${({ theme }) => theme.colors.danger.backgroundStrong};
Bien vu 🙏

2021-12-14 09:44 UTC, chambo-e approved these changes

2021-12-14 15:20 UTC, merged